const WEB_APP_URL="https://script.google.com/macros/s/AKfycbwsyNf7WJjnyZdKc9kNIuN0Vf8D26tG6ORWYXA3R4_VfjcSUqLS8p7_8Uc_aIL3SsSMJA/exec";
const MAX_FILES=10,MAX_IMAGE_SIZE=2600,JPEG_QUALITY=.92;
const photo=document.getElementById("photo"),processButton=document.getElementById("process"),fileList=document.getElementById("fileList"),msg=document.getElementById("msg"),batchResults=document.getElementById("batchResults"),totalEl=document.getElementById("total"),csvButton=document.getElementById("csv");
let selectedFiles=[],allResults=[];
function setMsg(t){if(msg)msg.textContent=t}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function updateButton(){if(processButton)processButton.textContent=`🤖 PERIKSA ${selectedFiles.length} FOTO DENGAN AI`}
function renderFileList(){if(!fileList)return;fileList.innerHTML=selectedFiles.map((f,i)=>`<div class="file-item"><span>${i+1}. ${esc(f.name)}</span><span>${(f.size/1048576).toFixed(1)} MB</span></div>`).join("");updateButton()}
function addFiles(files){const all=[...selectedFiles,...Array.from(files||[])],seen=new Set(),unique=[];for(const f of all){const k=`${f.name}|${f.size}|${f.lastModified}`;if(!seen.has(k)){seen.add(k);unique.push(f)}}selectedFiles=unique.slice(0,MAX_FILES);setMsg(`[${selectedFiles.length} foto siap diperiksa.`.replace("\u001b[",""));if(all.length>MAX_FILES)setMsg("Maksimal 10 foto. Foto setelah nomor 10 tidak dimasukkan.");renderFileList()}
photo?.addEventListener("change",()=>{addFiles(photo.files);photo.value=""});
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);let w=img.naturalWidth,h=img.naturalHeight;if(!w||!h)return reject(new Error("Ukuran foto tidak dapat dibaca."));if(w>MAX_IMAGE_SIZE||h>MAX_IMAGE_SIZE){if(w>=h){h=Math.round(h*MAX_IMAGE_SIZE/w);w=MAX_IMAGE_SIZE}else{w=Math.round(w*MAX_IMAGE_SIZE/h);h=MAX_IMAGE_SIZE}}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:false});if(!ctx)return reject(new Error("Browser tidak mendukung pemrosesan foto."));ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(img,0,0,w,h);c.toBlob(b=>b?resolve(new File([b],"lembar-jawaban.jpg",{type:"image/jpeg",lastModified:Date.now()})):reject(new Error("Foto gagal dikompres.")),"image/jpeg",JPEG_QUALITY)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error(`Foto "${file.name}" tidak dapat dibaca.`))};img.src=url})}
function toBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||""),i=s.indexOf(",");i<0?reject(new Error("Format foto tidak valid.")):resolve(s.slice(i+1))};r.onerror=()=>reject(new Error("Foto gagal dibaca."));r.readAsDataURL(file)})}
async function sendOne(file,i,total){setMsg(`Memproses foto ${i}/${total}: ${file.name}`);const compressed=await compressImage(file),base64=await toBase64(compressed),res=await fetch(WEB_APP_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({image:base64,mimeType:"image/jpeg"})}),raw=await res.text();let data;try{data=JSON.parse(raw)}catch{throw new Error(`Server mengirim respons tidak valid untuk foto ${i}.`)}if(!res.ok||!data.success)throw new Error(data?.error||`Server gagal (${res.status}).`);return data.result}
function normalize(r){const list=Array.isArray(r?.answers)?r.answers:[];let total=0,check=false,answers=[];for(let i=0;i<5;i++){const x=list[i]||{};let score=Number(x.score);if(!Number.isFinite(score))score=0;score=Math.max(0,Math.min(20,score));let conf=Number(x.confidence);if(!Number.isFinite(conf))conf=0;if(conf<.75)check=true;total+=score;answers.push({question:Number(x.question)||i+1,answer:x.answer||x.extracted_answer||"",score,confidence:conf,note:x.note||x.reason||""})}return{answers,total,status:r?.status==="PERIKSA"||check?"PERIKSA":"OK"}}
function render(){if(!batchResults)return;if(!allResults.length){batchResults.innerHTML="";return}batchResults.innerHTML=allResults.map((x,i)=>{const r=x.result;if(x.error)return`<div class="student-result"><div class="student-head"><h3>📄 Lembar ${i+1}</h3><strong class="check">GAGAL</strong></div><div class="meta">${esc(x.file.name)}</div><div class="answer">${esc(x.error)}</div></div>`;return`<div class="student-result"><div class="student-head"><h3>📄 Lembar ${i+1}</h3><strong class="${r.status==='PERIKSA'?'check':'ok'}">${r.status} · ${r.total}/100</strong></div><div class="meta">${esc(x.file.name)}</div>${r.answers.map(a=>`<div class="answer"><h3>Soal ${a.question} — ${a.score}/20</h3><div class="meta">Confidence pembacaan: ${Math.round(a.confidence*100)}%</div><div style="white-space:pre-wrap;margin:10px 0">${esc(a.answer)}</div><div class="meta">${esc(a.note)}</div></div>`).join("")}</div>`}).join("");const sum=allResults.reduce((s,x)=>s+Number(x.result?.total||0),0);if(totalEl)totalEl.textContent=`Total seluruh nilai: ${sum} (${allResults.length} lembar)`}
async function processAll(){if(!selectedFiles.length)return alert("Silakan pilih minimal 1 foto.");allResults=[];render();processButton.disabled=true;try{for(let i=0;i<selectedFiles.length;i++){try{const r=await sendOne(selectedFiles[i],i+1,selectedFiles.length);allResults.push({file:selectedFiles[i],result:normalize(r)})}catch(e){allResults.push({file:selectedFiles[i],error:e.message||"Gagal",result:{answers:[],total:0,status:"GAGAL"}})}render()}const failed=allResults.filter(x=>x.error).length;setMsg(failed?`Selesai. ${allResults.length-failed} berhasil, ${failed} gagal.`:`Selesai memeriksa ${allResults.length} lembar.`)}finally{processButton.disabled=false;updateButton()}}
processButton?.addEventListener("click",processAll);
csvButton?.addEventListener("click",()=>{if(!allResults.length)return alert("Belum ada hasil.");const rows=[["No","Nama","Kelas","Nomor Ujian","Q1","Q2","Q3","Q4","Q5","Total","Status"]],name=document.getElementById("name")?.value||"",cls=document.getElementById("class2")?.value||"",num=document.getElementById("number")?.value||"";allResults.forEach((x,i)=>{const s=(x.result?.answers||[]).map(a=>a.score);while(s.length<5)s.push("");rows.push([i+1,name,cls,num,...s.slice(0,5),x.result?.total||0,x.result?.status||"GAGAL"])});const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="hasil-penilaian-ai.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)});
updateButton();
